### ISSUE TITLE
Wanted to make sure you saw this

### ISSUE THREAD

**Issue by dmarx** [jawerty/AlienFeed#1]
I responded to your release of this project on reddit with several recommendations. I ultimately produced a refactored version of your code to illustrate ways to improve your coding practice (I put it in a gist instead of making a pull request because I just want you to see the code, I don't need to be a contributor to your project). I never received a response to my recommendations and you since deleted the post. I just wanted to make sure you saw this. Please review the code below, keeping in mind the significant difference in readability between my code and yours. 

https://gist.github.com/dmarx/4947902

I understand you are young and learning, and I hope you find my criticisms constructive. Keep up that enthusiasm, don't let programming get boring.

**Comment by jawerty** [comment]
Wow thanks man. I didn't see your post actually. Good to know there are
veteran programmers looking out.

**Comment by jawerty** [comment]
This is really modularized. Can I make the push with this code you
refactored.

**Comment by dmarx** [comment]
Knock yourself out. I'm pretty sure you're going to need to modify setup.py since this changes the entry point.
