### ISSUE TITLE
-o argument isn't working at all

### ISSUE THREAD

**Issue by phazonoverload** [jawerty/AlienFeed#17]
I'm running OSX 10.9 and installed aliendfeed via the python script in the master branch of this repo.

**Comment by jawerty** [comment]
Can you show me the log message you got?

On Monday, March 10, 2014, Kevin Lewis notifications@github.com wrote:

> I'm running OSX 10.9 and installed aliendfeed via the python script in the
> master branch of this repo.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/jawerty/AlienFeed/issues/17
> .

## 

Sent from Gmail Mobile -Jared

**Comment by phazonoverload** [comment]
How do I dump a log? It just ignores the -o argument. 

If I type `alienfeed aww -o 4` (which should open the fourth link), it outputs the top 
10 links

**Comment by jawerty** [comment]
That's interesting. I have the same computer and it works find. Can you run this code for webbrowser and tell me what happens 

```
import webbrowser
webbrowser.open("http://github.com/jawerty/AlienFeed")
```

**Comment by raulrene** [comment]
@jawerty , I have downloaded and set up today the library and while I was playing with it I bumped into this issue. I saw that it is already logged so I attempted a quick-fix. When you have time, please take a look at #18.

Thanks in advance
