### ISSUE TITLE
iTerm2: Terminal Colors 

### ISSUE THREAD

**Issue by jvtrigueros** [jawerty/AlienFeed#3]
Terminal colors for iTerm2 aren't being displayed. I don't know if this is an issue with my setup or with the way the colors are being set. It works just fine on Terminal.

I'm using iTerm2 on OSX 10.8
![alienfeed-iterm2-colors](https://f.cloud.github.com/assets/151656/1483416/46e3c93e-46f7-11e3-8d3b-5eee2f60e2c4.png)

**Comment by jawerty** [comment]
There might be something wrong with your setup considering the actual color code isn't showing up and it works on my iTerm2 on the same system. However, I might be wrong. If someone else has this problem, it would be helpful to chime in.

**Comment by danthegoodman** [comment]
I use iTerm2 and the colors work for me. 

iTerm2: Build 1.0.0.20130624
OSX 10.8.5
