### ISSUE TITLE
Opening a post should be opened in the terminal as well

### ISSUE THREAD

**Issue by jonalmeida** [jawerty/AlienFeed#7]
When you click on an option that is only text, it would be nice if you could get all the comments, put it in a file and call 'more' on it so that it's viewable entirely on your terminal.

I realize it's a big ask, but this was the impression I had that alienfeed would do when I installed it, so it would be nice to have this.

Awesome job so far! :)

**Comment by jawerty** [comment]
I agree. This is something that I have been wanting to add to the project.
Thanks for the request. I will try to comment my progress.

On Thu, Nov 7, 2013 at 5:51 PM, Jonathan Almeida
notifications@github.comwrote:

> When you click on an option that is only text, it would be nice if you
> could get all the comments, put it in a file and call 'more' on it so that
> it's viewable entirely on your terminal.
> 
> I realize it's a big ask, but this was the impression I had that alienfeed
> would do when I installed it, so it would be nice to have this.
> 
> Awesome job so far! :)
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/jawerty/AlienFeed/issues/7
> .

## 

<Jared>

**Comment by karan** [comment]
I'll be working on getting comments within the terminal. Is that ok @jawerty?

**Comment by jawerty** [comment]
Sure, that's alright. As long as it fits with the overall design of
alienfeed.

On Fri, Nov 8, 2013 at 6:00 PM, Karan Goel notifications@github.com wrote:

> I'll be working on getting comments within the terminal. Is that ok
> @jawerty https://github.com/jawerty?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/jawerty/AlienFeed/issues/7#issuecomment-28105277
> .

## 

<Jared>

**Comment by karan** [comment]
Yeah I'll try to keep it as consistent as possible.
